#!/bin/sh

sudo apt install libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0 -y
sudo apt install python3-pyqt5 python3-pyqt5.qtwebengine python3-pyqt5.qtwebchannel libqt5webkit5-dev -y
sudo apt install mongodb

sudo systemctl enable mongodb
sudo systemctl start mongodb

#python3 -m venv venv
#source venv/bin/activate

python3 -m pip install -e .